### ISSUE TITLE
标签页面的副标题该怎么设置呢？

### ISSUE THREAD

**Issue by fangqian** [LeslieZhu/OrgNote#14]
开始的副标题是配置文件中的那个subtitle,每篇博文的副标题是博文名，这是没有问题的
    但是，我把我的博客和你的一对比，问题就被发现了，你的标签页的副标题是一段不同于标签名的话，这让我觉得很酷。。但我的却是标签名，这让我感到无比失落。有设置这个的地方吗？如果有，在哪呢？

**Comment by LeslieZhu** [comment]
哦，我这是单独加了一点料，暂时OrgNote提供的配置无法做到不同主题里面使用不同的标签。最近准备重构一下OrgNote，到时候把这个功能加上。:-)
